
let arr_search_heading = ['pitch boundary', 'goal', 'penality', 'circle'];

let arr_search_description = [
    '<p>The pitch is rectangular in shape. The longer sides are called touchlines and the shorter sides are called the goal lines. The two goal lines are between 45 and 90 m (50 and 100 yd) wide and have to be of the same length. The two touchlines are between 90 and 120 m (100 and 130 yd) long and have to be of the same length. All lines on the ground are equally wide, not to exceed 12 cm (5 in). The corners of the pitch are marked by corner flags.</p> <p>For international matches the field dimensions are more tightly constrained; the goal lines are between 64 and 75m wide (70 and 82yds) and the touchlines are between 100 and 110 m (110 and 120 yd) long. The majority of top-level professional football pitches, including those belonging to teams in the English Premier League, measure 112 yards (102.4m) to 115 (105.2m) yards long and 70 yards (64.0m) to 75 yards (68.6m) wide.</p> <p>Although the term goal line is often taken to mean only that part of the line between the goalposts, in fact it refers to the complete line at either end of the pitch, from one corner flag to the other. In contrast the term byline (or by-line) is often used to refer to that portion of the goal line outside the goalposts. This term is commonly used in football commentaries and match descriptions, such as this example from a BBC match report: "Udeze gets to the left byline and his looping cross is cleared..."</p>',
    '<p>Goals are placed at the centre of each goal-line.[7] These consist of two upright posts placed equidistant from the corner flagposts, joined at the top by a horizontal crossbar. The inner edges of the posts are regulated to be 7.32 metres (24 ft) (wide) apart, and the lower edge of the crossbar is elevated to 2.44 metres (8 ft) above the pitch. As a result, the area that players shoot at is 17.86 sq. metres (192 sq. feet). Nets are usually placed behind the goal, though are not required by the Laws.</p><p>Goalposts and crossbars have to be white, and made of wood, metal or other approved material. Rules regarding the shape of goalposts and crossbars are somewhat more lenient, but they have to conform to a shape that does not pose a threat to players. Since the beginning of football there have always been goalposts, but the crossbar was not invented until 1875, before which a string between the goalposts was used.</p><p>A goal is scored when the ball wholly crosses the goal line between the goal-posts and beneath the crossbar, even if a defending player last touched the ball before it crossed the goal line (see own goal). A goal may, however, be ruled illegal (and void by the referee) if the player who scored or a member of their team commits an offence under any of the laws between the time the ball was previously out of play and the goal being scored. It is also deemed void if a player on the opposing team commits an offence before the ball has passed the line, as in the case of fouls being committed, a penalty awarded but the ball continued on a path that caused it to cross the goal line.</p><p>The football goal size for a junior match goal is approximately half the size of an adult sized match goal.</p>',
    '<p>Two rectangular boxes are marked out on the pitch in front of each goal.</p> <p>The goal area (colloquially the "six-yard box"), consists of the rectangle formed by the goal-line, two lines starting on the goal-line 5.5 metres (6 yd) from the goalposts and extending 5.5 metres (6 yd) into the pitch from the goal-line, and the line joining these, i.e. they are a rectangle 6yds by 20yds. Goal kicks and any free kick by the defending team may be taken from anywhere in this area. Indirect free kicks awarded to the attacking team within the goal area are taken from the point on the line parallel to the goal line (the "six-yard line") nearest where the infringement occurred; they cannot be taken any closer to the goal line. Similarly drop-balls that would otherwise occur closer to the goal line are taken on this line.</p> <p>he penalty area (colloquially "the 18-yard box" or just "the box") is similarly formed by the goal-line and lines extending from it, but its lines start 16.5 metres (18 yd) from the goalposts and extend 16.5 metres (18 yd) into the field. i.e. this is a rectangle 44yds by 18 yds. This area has a number of functions, the most prominent being to denote where the goalkeeper may handle the ball and where a foul by a defender, usually punished by a direct free kick, becomes punishable by a penalty kick. Both the goal and penalty areas were formed as semicircles until 1902.</p> <p>The penalty mark (colloquially "the penalty spot" or just "the spot") is 11 metres (12 yd) in front of the very centre of the goal: this is the point from where penalty kicks are taken.</p> <p>The penalty arc (colloquially "the D") is marked from the outside edge of the penalty area, 9.15 metres (10 yd) from the penalty mark; this, along with the penalty area, marks an exclusion zone for all players other than the penalty kicker and defending goalkeeper during a penalty kick.</p>',
    '<p>The centre circle is marked at 9.15 metres (10 yd) from the centre mark. Similar to the penalty arc, this indicates the minimum distance that opposing players have to keep at kick-off; the ball itself is placed on the centre mark.[13] During penalty shootouts all players other than the two goalkeepers and the current kicker are required to remain within this circle.</p>'
]

let isFound = false;
$(document).ready(function(){
    $("#search-btn").click(function(){ 
        let search_input = $('#search-input').val();

        for(let i =0; i<arr_search_heading.length; i++){
            if(search_input.toLowerCase() == arr_search_heading[i]){
                isFound = true;
                $('#print-search-heading').text(arr_search_heading[i].toUpperCase());
               $(arr_search_description[i]).appendTo('#print-search-desc');
                break;
            }
        }
        if(!isFound){
            $('#print-search-desc').text("Not Found......Please enter another word..");
        }
    }); 
});
